# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Wimble Robotics
scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: 0.0
        upper_angle: 6.28319  # 2*PI
# scan_to_scan_filter_chain:
#   ros__parameters:
#     filter1:
#       name: box_filter
#       type: laser_filters/LaserScanRangeFilter
#       params:
#         use_message_range_limits: false   # if not specified defaults to false
#         lower_threshold: 0.5              # if not specified defaults to 0.0
#         upper_threshold: 0.7              # if not specified defaults to 100000.0
#         lower_replacement_value: -.inf    # if not specified defaults to NaN
#         upper_replacement_value: .inf     # if not specified defaults to NaN