batter_voltage_overlay:
  ros__parameters:
    input_topic_name: /sigyn/teensy_bridge/battery/status
    input_message_type: sensor_msgs/msg/BatteryState
    output_topic_name: /battery_voltage_overlay
    output_message_type: min_max_curr_rviz_overlay/msg/MinMaxCurr
    field_mappings_str: "voltage:current"
    static_fields_str: "min=0.0,max=42.0,compact=true,title=Batt"
